<?php

namespace AlunoBundle\Repository;

/**
 * AlunosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlunosRepository extends \Doctrine\ORM\EntityRepository
{
}
