<?php

namespace AlunoBundle\Repository;

/**
 * AlunoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlunoRepository extends \Doctrine\ORM\EntityRepository {
}
